name: ae2f-workflow
on:
  push:
    branches: [main]
    
jobs:
  test-compiler-majours:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

        include:
          - os: ubuntu-latest
            bash: sh

          - os: windows-latest
            bash: bash

          - os: macos-latest
            bash: sh

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'
        fetch-depth: '1'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Test
      run: ${{ matrix.bash }} ./test.sh
        
  
